services:

  migrate:
    container_name: migrate
    image: migrate/migrate:v4.19.1
    volumes:
      - ../../database/rds/migrations:/migrations
    command: >
      -path=/migrations
      -database postgresql://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_ENDPOINT}:${RDS_PORT}/${DEV_RDS_NAME}?sslmode=${RDS_SSL_MODE}
      up

  api-server:
    container_name: api-server
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      context: ../../backend
      dockerfile: docker/Dockerfile.dev
    working_dir: /SignalEagle
    environment:
      STAGE: dev
      AWS_REGION: ${REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RDS_HOST: ${RDS_ENDPOINT}
      RDS_USER: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_NAME: ${DEV_RDS_NAME}
      RDS_PORT: ${RDS_PORT}
      RDS_SSL_MODE: ${RDS_SSL_MODE}
      JWT_SECRET_KEY: supersecretkey123
      TOKEN_EXPIRES_IN_HOURS: 1
    ports:
      - "3000:3000"
    volumes:
      - ../../backend/app:/SignalEagle
